### ISSUE TITLE
Feature : Image preview for blob columns

### ISSUE THREAD

**Issue by windware** [hankinsoft/SQLPro#127]
It would be convenient to have an image preview feature for blob columns when double clicked on it, if it could detect it as some sort of image format.

**Comment by davidharrison92** [comment]
Most commonly we have PDFs stored. I don't know if Mac OS lets you use the Quick Look feature, but that seems to cover most things.

**Comment by hankinsoft** [comment]
One of the things I'm doing for the image preview is detecting data types and displaying more details in the results grid. What do you guys think of this format?

<img width="929" alt="image" src="https://user-images.githubusercontent.com/3160528/31277300-a9c5aa90-aa76-11e7-9160-67a4851f7f2c.png">

Specifically, the `image` column. If the data type can be detected the type & size will be displayed. If the data type cannot be detected then it falls back to the old hex display.

**Comment by windware** [comment]
It looks good. Is it possible to preview the content as well somehow for the detected column?

Also, how would the performance be for displaying 100s of rows?

**Comment by hankinsoft** [comment]
Yep, you will be able to preview the contents similar to textfield. Here is what its looking like: http://recordit.co/Y1R79xvJ0D.

I'm working on caching for performance improvements now. Its fairly quick to begin with as the data type detection only needs roughly the first ~10 bytes of a file. With additional caching the performance should be great.

**Comment by windware** [comment]
Screen capture looks great.

**Comment by hankinsoft** [comment]
Hi,
I have a test version available here:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.147.app.zip

Could you give this a try?

Notes.

1. Editing in the preview image cell is not yet supported, so you will always see readonly at the moment.

2. Only MSSQL and MySQL currently support previewing images and PDFs.

3. PDFs will only display the first page. You will need to press the gear -> open in preview to view the full document.

4. This works a bit different than the current text edit/preview. Those use a ‘popup’ window, where the image preview uses a modal dialog. This is because the image preview allows the export option which then displays a save panel. This cannot be done from a popup. I’m thinking I will convert all of the current popups to use this same system as I personally like it better.

**Comment by windware** [comment]
I've tested with JPG and PDF and looks great. It's better than SequelPro as it doesn't tell what file type it is but only shows the ascii representation of the first bit.

If I have to mention, when exporting, it would be friendly to give the file extension of the file being displayed as the exporting file name by default. (Like .jpg, .pdf)

**Comment by hankinsoft** [comment]
I've added the extension visible by default in this build: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.1.0.149.app.zip it will also fix #149 .

**Comment by windware** [comment]
Excellent. If I have to nit pick, it may be easier to show the preview by double clicking the column cell, instead of on the small arrow icon.
