### ISSUE TITLE
can I remove the "sample connections" from the connect window?

### ISSUE THREAD

**Issue by hitgeek** [hankinsoft/SQLPro#175]

**Comment by unikitty37** [comment]
This.

I didn't ask for a sample connection — it appeared on upgrading to a new version (btw, please use Sparkle rather than making people unpack zips and drag them about the place to install).

The remove button is greyed when selecting the sample connection. It is not greyed when selecting my own connection. I want to keep my own connection. I do not want to keep the sample connection.

Forcing it to remain on my screen the whole time just feels arrogant, TBH. Let me delete it — or even **ask my permission before adding it in the first place**!

**Comment by kinnell** [comment]
Why was this even deemed a good idea?

This is something that is only useful for someone who is using your app for the first time and maybe the second time - it's a nuisance for anyone else.

You will see happier users when you design your software so that they are able to do what they are using your software to do. For this app, that is:

1. Find and connect to a server
2. Select a database and connect
3. Write and execute SQL

Showing sample connections makes finding the the right server to connect to much harder. Perhaps the sample connections are only shown until the user adds their own connections, but adding these connections without letting the user remove them makes no sense.

**Comment by hankinsoft** [comment]
I've added an option to disable sample connections to the next release. Should be available early next week.
