### ISSUE TITLE
Database Filter in Sidebar Search 

### ISSUE THREAD

**Issue by davidharrison92** [hankinsoft/SQLPro#180]
Hi There,

It'd be great to have the option to search only in one DB (either a search term like DBNAME:Table or a second filter in that panel perhaps?)

Cheers

**Comment by hankinsoft** [comment]
Hi,
Would something like Xcode's search work? Basically underneath the search field is a 'Scope' button. Pressing this opens up 'basically another instance of the database tree', but you can select one or more node (so you could select one or more databases, or just select the 'tables' node, etc). Then searching would be limited to this scope of objects you selected?

**Comment by mwhite05** [comment]
@hankinsoft 

I think what I'm looking for is a little different from what you describe, though your suggestion would be useful as well. I tried out the scoped search in Xcode and it seems that it searches within the selected top level nodes. The problem for us is mostly in narrowing the list of top level nodes from 200+ to just a few that match a specific name or prefix.

I did find that in SQLPro I can click one of the databases in the list and start typing and it focuses and selects the node matching that text. However, because we have over 200 databases grouped by prefixes we have to type a lot of characters for that to be useful and a single typo throws it off and we have to start over. I'm familiar with this issue because our current database tool has the same functionality for finding a specific database and I'd like to find a tool that actually filters the list of shown databases down to only what matches the search text.

Once we have at least narrowed the database list down to a specific prefix then I could see the scoped search being useful as we could easily hi-light one or two specific databases from the list and apply a table name search to just those nodes.

**Comment by hankinsoft** [comment]
Thanks for the details. I think I've got a solution that will work for everything. I can explain it best through a video:

![CleanShot 2019-10-23 at 12 35 19](https://user-images.githubusercontent.com/3160528/67410018-d4288880-f591-11e9-9ca2-43f3aabcf1f0.gif)

Clicking the `search everywhere` toggle will let you choose one or more search locations. In addition, there is a `database filter` at the top which will let you narrow down the list of possible databases.

Because this includes more options than previously, this will be in its own 'tab' (as seen at the start of the video - switching from the database tree to the search tab). The find shortcut will automatically switch you to this tab + focus the search field as well.

If you get the chance, please let me know your thoughts.

**Comment by hankinsoft** [comment]
Also, just to note additional search options are being added as well (backend is done, UI is still in progress). New options will include search type (contains, begins with, ends with and regular expression) along with a case insensitive/specific option.

**Comment by mwhite05** [comment]
This looks great! 👍 to the regex and case sensitive toggle too.

**Comment by hankinsoft** [comment]
If you get the chance, please give the following build a try:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.48.2.app.zip

This includes all of the changes chatted about above. I'm looking for any feedback or issues and to confirm if it solves what you are looking for. (This build should also sort #312).

Known issues: If you collapse the database tree while on the 'search' tab your UI will mess up. You will need to close and re-open the app for it to become fixed.

Please don't replace your existing build with this one - in my testing its stable, but the updated searching is a pretty major change and could have issues I've not yet seen.

**Comment by mwhite05** [comment]
Granted, I'm on the latest Catalina beta build right now, but I tested the search and when I click the "Search Everywhere" button it is giving me the pinwheel of death and I end up having to force quit the application. Let me know if you need any sort of crash reports or debug info about it and how to get it.

**Comment by hankinsoft** [comment]
Thanks for the feedback - a few questions:

> it is giving me the pinwheel of death

How many databases do you have on the server you were attempting to search? (Just trying time figure out why you might get the spin you pinwheel).

> The sidebar does not initially show the tree data (it's just blank)
> The tree data shows after I press Return while focused on the search input field in the new search panel.

Hmmm, you would prefer the tree data to be visible when you first switch to it? Or a better indicator that you need to ‘initialize’ the search first. I was thinking most use cases would want to type something before having data visible - xcodes search shows a little ‘x results’ header - maybe if I add that in it might make it a bit more user friendly?

> When searching with the default option of "Search everywhere" for a database name, nothing is shown but searching by a table name still works in the new context.

My thinking is that this overall search returns objects ‘from within the databases’, not the databases itself - the second panel (the everything filter that you doesn’t see to be able to open) contains the ‘database scope’ filter. Hopefully this will be a bit clearer once I’ve fixed the spin you wheel issue you are seeing - I’ll do some more testing with that and hopefully I can reproduce.

Thanks for giving this a try BTW.

**Comment by mwhite05** [comment]
I was attempting to search our main server which has about 230 databases and between 50 & 80 tables each on average.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Ah, good point. The tree does not need to initialize first for that tab.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

That makes sense; I just initially expected "everything" to include the databases in the new search tab. It sounds like that new search tab's default behavior is to essentially behave like the original search field does in the other tab and then search by database name only with the "database scope" option selected?

I'm happy to test it :) Just let me know when you have another build and I'll put it through another round.

**Comment by hankinsoft** [comment]
Hi,
I've posted an updated build available here:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.49.app.zip

Please give it a try. Below is a quick example where I use the database filter to only show databases starting with 'db_' and then select two databases to search in is available here:

![CleanShot 2019-10-29 at 12 31 39](https://user-images.githubusercontent.com/3160528/67784224-324de380-fa4a-11e9-93d7-69e74e6c1140.gif)

I think that is similar to what you are attempting to do and should not have the spinning wheel of death anymore.

**Comment by mwhite05** [comment]
This is working now. I might be getting a bit picky but is there a possibility to have it only expand a database node if it matches a table name inside? With the number of databases we have for a given prefix it creates a long scrolling list when the db nodes are expanded.

**All db nodes collapsed**
<img width="185" alt="Screenshot 2019-10-30 09 09 34" src="https://user-images.githubusercontent.com/11068771/67860748-08053000-faf5-11e9-90bf-7d74cf205e5c.png">

**All db nodes expanded** (current behavior)
<img width="187" alt="Screen Shot 2019-10-30 at 9 15 52 AM" src="https://user-images.githubusercontent.com/11068771/67861142-ece6f000-faf5-11e9-96e3-2ad34a1a28aa.png">

**Comment by hankinsoft** [comment]
> I might be getting a bit picky but is there a possibility to have it only expand a database node if it matches a sub-node?

Hmm, in the picker you are listing no sub-node matching is done. Maybe I'll just initialize database nodes as collapsed when you filter them? Would that do the trick?

**Comment by mwhite05** [comment]
Yep, that would work just fine. :)

**Comment by hankinsoft** [comment]
The above mentioned changes have been added for this build: https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2019.50.app.zip.

**Comment by mwhite05** [comment]
Sorry for the delayed response. I checked out the latest build and it does just what I need now. Thank you!
