### ISSUE TITLE
import csv crashes if apostrophes in column headers after selecting new table

### ISSUE THREAD

**Issue by hitgeek** [hankinsoft/SQLPro#222]
pretty rare case, bug the app crashes when trying to import into a new table with the headers contain apostrophes. removing the apostrophes resolved the crash. 

seems to crash when trying to auto-generate the column names (right after you click "new table")

**Comment by hankinsoft** [comment]
I'm just trying to reproduce this, but so far I've been unable to. What
type of database are you attempting to import into? Any chance you could
share a sample csv file?

**Comment by hitgeek** [comment]
here is a sample. not sure if the apostrophes are actually the problem, because it seems like Excel changes a fews things with this file if you open and re-save it, and that seems to fix it, even without changing anything. 

[0417monm200320.txt](https://github.com/hankinsoft/SQLPro/files/2617895/0417monm200320.txt)

trying to import this file as is, seems to crash the app. importing after saving the file in excel works. 

i'm going to close this b/c the underlying problem is this weird csv.

**Comment by hankinsoft** [comment]
Thanks, FYI I've added a fix to the crash in the next build. When SQLPro reads that csv file it finds the data row has more entries (32) than header columns (30) and it skips the row. Since only one data row exists (and it gets skipped) a null exception happens. I've changed the code to handle the first 30 entries rather than skip the row completely and display a warning to the user.
