### ISSUE TITLE
Wrong title in start menu listing for Windows version

### ISSUE THREAD

**Issue by patrick330602** [hankinsoft/SQLPro#321]
![image](https://user-images.githubusercontent.com/15316889/68522361-609eaf00-02e5-11ea-9ccd-e6ca63e485f9.png)

I download SQLPro Studio from the Microsoft Store, but the name showed is "SQLPro for MSSQL".

**Comment by hankinsoft** [comment]
Thanks, I’ll get this fixed for the next build. FYI I’m planning on making a big push of improvements on the windows versions in the next couple of months - they are a bit behind the macOS version at the moment.

**Comment by jim256** [comment]
@hankinsoft awesome to hear that the Windows version is slated for a big push over the next little while! I'm currently using another tool on Windows (I use Windows about 30% of the time) because of it's being a little behind, and would *really* like to be on SQLPro Studio all the time because of how great it is.
Looking forward to it!

**Comment by hankinsoft** [comment]
New version has been approved on the App Store and should be available for update shortly. That should resolve the title issue. If you get the chance, please let me know if that sorts it for you.

**Comment by patrick330602** [comment]
Tested and the issue is resolved! thank you for your work😃
