### ISSUE TITLE
Inline update fails on some fields with error, "Incorrect Syntax near keyword 'END'"

### ISSUE THREAD

**Issue by William-Sheehan** [hankinsoft/SQLPro#322]
Upon upgrading to new version (2019.54 (Build 10486)), I now _sometimes_ receive this error when attempting to to an inline record edit from the results set. 

It seems to only happen on varchar fields, (but this is based only on observation) I don't know for sure.  

<img width="427" alt="Screenshot 2019-11-13 10 47 04" src="https://user-images.githubusercontent.com/2464096/68779732-25f98700-0603-11ea-98ce-e3eee80a9ffe.png">

Any assistance or suggestions would be greatly appreciated. 

Here's the DDL for the table on which I was attempting to do an in line update: 
```
CREATE TABLE [dbo].[ProcessItemCheckPointDatesHistory](
	[PichPK] [int] IDENTITY(1,1) NOT NULL,
	[PichSharedSvcProcessItemFk] [int] NULL,
	[PichCheckPointTypeFK] [int] NULL,
	[PichCreateDate] [datetime] NULL,
	[PichStatusFK] [int] NULL,
	[PichStatusDate] [datetime] NULL,
	[PichStatusUserLogin] [varchar](20) NULL,
	[PichStartDate] [datetime] NULL,
	[PichStopDate] [datetime] NULL,
 CONSTRAINT [PK_ProcessItemCheckPointDatesHistory] PRIMARY KEY CLUSTERED 
(
	[PichPK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```
And here is the select statement, the result set of which I was attempting to perform an inline edit. 

```
SELECT * FROM dbo.ProcessItemCheckPointDatesHistory
WHERE  
PichSharedSvcProcessItemFk = 315537
```
I was attempting to set the value of the field PichStatusUserLogin to **Unk**

I am able to make this update by writing and executing an update statement. 

I have experienced this problem with other fields on other tables since upgrading to the new version. I've never had this issue with earlier versions.

**Comment by hankinsoft** [comment]
Sorry about that. I’ve got a big update for editing results that will be available early next week which should sort this out.

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2019.57.app.zip?

A few notes:
Changes are no longer applied as soon as you make them. Instead, when a change is made, a new bar will appear at the bottom of the results (as seen here):

![CleanShot 2019-11-19 at 10 01 39](https://user-images.githubusercontent.com/3160528/69152971-c7755280-0ab3-11ea-853e-c1ffadec1f1b.gif)

If your table has primary keys, the where statement should be 'WHERE pk = pkValue'. Otherwise, if the table does not have primary keys the where statement will be a combination of the row values `WHERE row1 = row1Value AND row2 = row2value, etc.`.

I THINK in your case, even though you have primary keys, you will still see the second statement. If thats the case, please let me know as there may be one more issue to get sorted out.

**Comment by rc125** [comment]
Same problem here, any ETA on this release?

**Comment by hankinsoft** [comment]
@rc125 can you try the build listed above and see if that sorts the issue for you? (https://d3fwkemdw8spx3.cloudfront.net/mssql/SQLProMSSQL.2019.57.app.zip).

**Comment by hankinsoft** [comment]
This has been released for all the latest versions of the apps.
