### ISSUE TITLE
Bug: Autocomplete window appears in bottom-left corner of screen

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#377]
@hankinsoft Sometimes, the autocomplete suggestion window appears in the bottom-left corner of the screen, and never goes away (even after accepting a suggestion, closing tabs, opening tabs, etc.) until the application is quit and re-opened.

I haven't noticed a pattern. Just thought I'd get this on your radar. It doesn't happen very often. I'll capture logs for the next time it does.

**Comment by hankinsoft** [comment]
Have you ever seen this again?

**Comment by jim256** [comment]
@hankinsoft , it's very rare, but it does continue to happen. I did see it about 4 days ago, but I was in a rush and didn't take the time to get the log, redact all the info, and post here, for which I apologize. Will try to get it next time.

**Comment by hankinsoft** [comment]
2020.61 is now available which I made a small changes around autocomplete positioning. If you see this again, let me know - otherwise I'll wait about a month then close it.

**Comment by jim256** [comment]
@hankinsoft, awesome news. You have been one busy guy this last weekend! Very cool to see all the improvements.

Sounds good.

**Comment by hankinsoft** [comment]
FYI althought I thought I had fixed this, during the last build I reproduced this. It was happening if autocomplete was triggered when the cursor was scrolled off-screen (easily reproducible by moving the cursor to the end of a large script, then scrolling to the top so that the cursor is not visible, then hitting escape).

I've sorted this for the latest build by detecting this and scrolling to the proper position before displaying the autocomplete window (this is what Xcode does as well). If for some reason you see this again after 2020.96, please let me know.

**Comment by jim256** [comment]
Awesome! I thought I'd maybe seen it a time or two and meant to comment here.

I appreciate your catching it. I'll remember to post here again if I see it after 2020.96.
