### ISSUE TITLE
the last version 2020.28 of SQLPro for postgres crashes each time I exec an action on a table 

### ISSUE THREAD

**Issue by ogattaz** [hankinsoft/SQLPro#382]
I just got the last version 2020.28 of SQLPro for postgres using the Apple's Appstore.

I can open a connection to my local database server (cf. v11.6), I can browse the schemas of the databases, but each time  I try to exec one of the listed actions below SQLPro crashes.
select top 1000 rows
new query
When I try to exec "duplicate table", the "from table" dropdown list is empty and SQLPro refuses to duplicate the original table even if the "target table" field contains the right generated name using the name of the original one.

[SQLPro for Postgres_2020-03-10-180958_macbookolivier.crash.txt](https://github.com/hankinsoft/SQLPro/files/4313826/SQLPro.for.Postgres_2020-03-10-180958_macbookolivier.crash.txt)

The context:
  Version 2020.28 (Build 1047804.5)
 My subscription to SQLPro Premium expires: 10 July 2020

  Identifiant du modèle :	MacBookPro11,4
  Nom du processeur :	Quad-Core Intel Core i7
  Vitesse du processeur :	2,5 GHz
  Nombre de processeurs :	1
  Nombre total de cœurs :	4
  Cache de niveau 2 (par cœur) :	256 Ko
  Cache de niveau 3 :	6 Mo
  Technologie Hyper-Threading :	Activé
  Mémoire :	16 Go
  Version de la ROM de démarrage :	196.0.0.0.0
  Version SMC (système) :	2.29f24

  Version du système :	macOS 10.15.3 (19D76)
  Version du noyau :	Darwin 19.3.0
  Volume de démarrage :	Macintosh HD
  Mode de démarrage :	Normal

**Comment by hankinsoft** [comment]
Very sorry about that! I've got a fix submitted to Apple, which usually takes less than 24 hours to be approved (its been ~12 hours so hopefully the fix is available soon). In the meantime I would suggest downloading https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.30.app.zip. That will let you use SQLPro Studio for seven days and should let you continue with hopefully minimal interruptions. Then once the SQLPro for Postgres build is available tomorrow you can switch back.

Again, sorry for the issue!

**Comment by hankinsoft** [comment]
The latest version is available in the App Store and multiple users have confirmed the fix. Please let me know if you still see any issues after updating. Again, sorry for the issue!
