### ISSUE TITLE
latest version 2020.08 crashes each time I try a New Query window

### ISSUE THREAD

**Issue by ca-ma-ra** [hankinsoft/SQLPro#383]
Version 2020.28 (Build 1047804.5)
Lifetime subscription

MacBook Air (Retina, 13-inch, 2018)
Processor 1.6 GHz Dual-Core Intel Core i5
Memory 8 GB 2133 MHz LPDDR3

**Comment by r3id** [comment]
Same here, every time I try to create a new query, or when I select "Select top 1000" the app is crashing on maOS

**Comment by hankinsoft** [comment]
Very sorry about that! I've got a fix submitted to Apple, which usually takes less than 24 hours to be approved (its been ~12 hours so hopefully the fix is available soon). In the meantime I would suggest downloading https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.30.app.zip. That will let you use SQLPro Studio for seven days and should let you continue with hopefully minimal interruptions. Then once the SQLPro for Postgres build is available tomorrow you can switch back.

Again, sorry for the issue!

**Comment by raimille1** [comment]
Same here! Tried many different options

**Comment by bptremblay** [comment]
I forget it's not easy to push to the App Store.

**Comment by raimille1** [comment]
Had to use PGAdmin today, reminded me how much the market needs SQLPro! 💪

**Comment by hankinsoft** [comment]
For some reason the update has still not gone in review (it’s been waiting for review for about ~30 hours). Hopefully sometime soon!

**Comment by ca-ma-ra** [comment]
Hope it gets to the store before my trial ends :)

**Comment by hankinsoft** [comment]
Build 2020.30 was approved roughly ~12 hours ago and should be in the store now. Please check the App Store for the update when you get the chance.

**Comment by r3id** [comment]
All sorted now, thanks guys 😄
