### ISSUE TITLE
Feature Request: Reduce autocomplete suggestion delay

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#394]
I'd like to see the autocomplete suggestions window pop up a bit more quickly. Ideally, it'd be nice to customize this in the preferences. But if not, it'd still be nice to have it pop up just a little bit more quickly.

Because of the delay, I usually don't use it unless I don't know the exact name of what I'm looking for. If I know the exact spelling, I'll usually opt to just hurry and type it myself. If the delay were reduced by about 40%, I think that would be perfect.

**Comment by hankinsoft** [comment]
Added for the next build. See [Autocomplete delay](https://www.sqlprostudio.com/blog/6-autocomplete-delay) for details.

**Comment by hankinsoft** [comment]
2020.61 is now available which adds this. If you get the chance, please give it a test and confirm its working as you would expect.

**Comment by jim256** [comment]
@hankinsoft, awesome!

A few notes:
1. Looks like there's a small typo in the docs :) : "... which allows users to **determins** the time it takes for the ..."
2. Can we also add "," (comma) as an exception character, so that the suggestion window doesn't pop up after typing a comma?
3. It does seem to sort of struggle to change the value. After change it and it "Apply and Close", it takes around ~8 seconds to apply. I don't personally care much, but thought I'd let you know in case you hadn't already noticed.

**Comment by hankinsoft** [comment]
Thanks for the notes. In response:

1. Fixed
2. Discussed below
3. Duplicate of 2?
4. When a preference is changed, ALL preferences are actually applied. The speed will depend on the number of tabs open, result sets open, plus a few other things. I can take a look and see if there are any `easy` wins for speed on this, but where its something people won't be doing often (preferences are usually set and forget) it's not something I want to put a ton of time into.
5. Sure, fixed for the next build. SQLPro does some 'context based suggestions' and AS was missing as one of the available keywords in that situation. I've sorted it.

So for item 2, currently I have these items causing autocomplete to not appear at all (unless you manually hit escape) which I was thinking was fine, EXCEPT for the instance of newlines/carriage returns.

Specifically think of:

<pre> SELECT * FROM abcdef;
 &lt;cursor is here&gt;</pre>

I think people might want autocomplete at this location. However in the case of

<pre>SELECT
    column1,
&lt;cursor is here&gt;</pre>

I don't think they would want it until they indent (which I think is where you are coming from)? I'm thinking for these special cases options, instead of autocomplete being 'cancelled' instead it is slowed - maybe too a delay of two seconds.

Thoughts?

**Comment by jim256** [comment]
1. 👍 
3. Yes. Oops.
4. Understood and agreed. In fact, the next time I changed them, it saved super quickly. Deserves 0 time in my personal opinion since it'll be so rare. I was just pointing out to make sure you were aware.
5. Awesome.

2. I would personally prefer to never have autocomplete suggest anything after a hard return. In both of the examples above, I would prefer no suggestions until I begin to type something. I personally don't want suggestions until I begin typing.

**Comment by hankinsoft** [comment]
I think we had finalized everything with this issue and it should be good to close? If I'm missing something, please let me know.

**Comment by jim256** [comment]
I'd personally still like to see #5 implemented. I personally don't like that it pops up with a suggestion on a blank line, forcing me to dismiss it if I'm not going to add more. Sometimes it causes random autocompletion if I decide to hit return another time to get an empty line and write more, because the suggestion pops up right before I hit the second return.

**Comment by hankinsoft** [comment]
Hi. Item five should actually be taken care of (sorry I don't think I mentioned that). If you are not seeing this behaviour, could you send a video?

**Comment by hankinsoft** [comment]
Nevermind, I've reproduced it.

**Comment by jim256** [comment]
This one is small but will still be really really nice to see improved. Thanks!

**Comment by hankinsoft** [comment]
This should be all sorted in the latest build. If you get the chance, please give it a try and let me know.

**Comment by jim256** [comment]
Looks to be all set. Thanks!
