### ISSUE TITLE
Feature Request: Copy Results as Monospace Table

### ISSUE THREAD

**Issue by danroyo** [hankinsoft/SQLPro#417]
My main use case would be to quickly dump query results into a Markdown document.  Although the basic markdown spec doesn't have a spec for tables, many formatters recognize monospaced tables:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

**Comment by hankinsoft** [comment]
Hi,
This already exists actually, it's just a bit hidden. Right click the results grid and choose 'Copy selected with headers as' -> 'Formatted Text (monospace)' or 'Formatted Text (markdown)'.

Markdown uses the document such as GitHub. Monospace uses spaces as padding so that a monospaced document looks properly formatted.

Please let me know if either of those do what you need?

**Comment by danroyo** [comment]
wow, actually i think you already support this
