### ISSUE TITLE
All Query History Lost

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#453]
Unfortunately, I don't have a log file for this one, because I'm not even sure when / how it happened.

At some point after I updated to 2020.59 (Build 110683.5), I went to look at my history, and there was none, which is really unfortunate.

I think I may have seen this happen a time or two after I right-clicked on a connection and clicked "Disconnect". How / when is query history purged?

macOS 10.15.5 (19F101)
Snowflake 4.21.3

**Comment by hankinsoft** [comment]
Ahhhh, I know what happened. When I first added query history, each history identifier was stored as a checksum of 'host, port, user, and maybe a few other items depending on connection type'. As part of #429, I've been switching a bunch of code to instead use the connectionId (an internal uuid generated when a connection is created). This way logging, etc has a connectionId in it rather than any identifiable details. I forgot that that change would effectively 'forget' query history.

On the plus side, that shouldn't happen again. You probably would have seen history disappear before if you changed any connection details, but that won't happen any more.

**Comment by jim256** [comment]
@hankinsoft, understood. Thanks!
