### ISSUE TITLE
Version 2020.84 (Build 110723) Reset Prefs?

### ISSUE THREAD

**Issue by nickv2002** [hankinsoft/SQLPro#500]
Hey I just downloaded SQLPro Studio Version 2020.84 (Build 110723)

Looks like all my prefs were reset by the new version for some reason? I got a prompt to re-authenticate my license key, but also lost the color/font prefs, keyboard shortcuts, etc. Everything was default as far as I could tell.

My bookmarks were still there though. But I lost my active tabs.

The new version also doesn't seem to register when I change my Appearance prefs at all so I'm stuck with the Default (Light) set.

Overall it's super weird, how can I redownload the previous version?

**Comment by hankinsoft** [comment]
Thank you, I see whats up. I was investigating adding support for MySQL sockets and I had removed sandboxing and forgot to re-enable it. This would give a few items a separate library path which is why the preferences would be reset. I've got a fixed build here:
https://d3fwkemdw8spx3.cloudfront.net/studio/SQLProStudio.2020.85.app.zip

Again, sorry for the issue!

**Comment by nickv2002** [comment]
Build you posted seems to work again. Thanks.
