### ISSUE TITLE
Feature Request: Find text input auto-populated by highlighted code viewer string

### ISSUE THREAD

**Issue by chrischain** [hankinsoft/SQLPro#624]
I'd like to see the Find functionality updated to automatically copy a highlighted string in the code viewer to the input box when the Find bar is opened (by menu or cmd-F). This is the way VS Code currently operates, and I think it would be helpful in SQLPro Studio too.

When no text is highlighted, then the current functionality of loading the last searched string should be kept.

This would be a great timesaver when searching large SPs or queries.

**Comment by jim256** [comment]
I also think this would be nice.

That said, I think I'd personally downvote it for now vs other requests and bugs, given that there is a pretty good workaround (doing CMD+C before CMD+F and CMD+V afterward).

Since some other request / bugs don't have any workaround, my personal vote would be to do this farther down the road.

**Comment by hankinsoft** [comment]
This was pretty easy, so I've got it added for the next build. I'll make another post once its available.

**Comment by chrischain** [comment]
Awesome! Thank you!

**Comment by jim256** [comment]
This is handy. Seems to be working well. Thanks!
