### ISSUE TITLE
iPad App does not recognize my subscription

### ISSUE THREAD

**Issue by pachocamacho1990** [hankinsoft/SQLPro#635]
I just downloaded the iPad app and it is not recognizing my paid subscription, the restore button is not working but I already work well from my Mac without any issue, is there any problem with the mobile app ?

**Comment by hankinsoft** [comment]
Hi,
Unfortunately iOS and macOS subscriptions purchased from the App Store are not shared. While Apple did add support for in app purchases to be shared between platforms, they only added support for NEW apps (SQLPro was already in the store ~4 years at that point).

Due to this, only subscription purchases from the webstore are cross-platform.

What I generally offer to customers who wish to switch to the webstore purchase, it to forward me (kyle@hankinsoft.com) their App Store purchases, and I can provide a promo code for the webstore to match - then use the webstore license going forward (the webstore license will work on the App Store).
