### ISSUE TITLE
"WAREHOUSE", "WAREHOUSES", "USER", and "USERS" always unnecessarily-escaped in double quotes.

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#638]
Similar to #527 

Whenever I accept an autocomplete suggestion for an object named `WAREHOUSE`, it always inserts it with double quotes:

`SELECT "WAREHOUSE"`

It isn't a reserved word in Snowflake and can be used without escaping.

SQLPro 2021.53 (Build 110808.5)
macOS 11.3.1 (20E241)
Snowflake 5.19.1

**Comment by jim256** [comment]
This also applies to `WAREHOUSES`, `USER`, and `USERS`.

For MySQL (8), I've also noticed this for `USERS`.

**Comment by hankinsoft** [comment]
Fixed for the next builds. I'm also taking a look at adding the keywords/functions list for each database type to this repository which will then be included as a sub-repository to my actual code. In addition, I'll be changing the format to accept documentation markup which will be a starting point for #626. Hoping to have this first change ready within the next couple of weeks.

**Comment by jim256** [comment]
That will be so awesome!!!!

**Comment by hankinsoft** [comment]
Fixed in submitted build (2021.56). Should be available within ~24 hours. For this version and on, this repository now contains the [keywords and functions](https://github.com/hankinsoft/SQLPro/tree/master/sql). I do need to add a bit of documentation as the keywords are not always used for autocomplete (but generally always for syntax highlighting). I will soon be adding to the `descriptionMarkup` field in functions and add support for displaying that in autocomplete.

**Comment by jim256** [comment]
Seems to be fixed.

Super excited about progress for #626.
