### ISSUE TITLE
Bug: Snowflake: Default database not recognized

### ISSUE THREAD

**Issue by jim256** [hankinsoft/SQLPro#669]
Often when I use the "Select top 1,000 rows" function (either by right-clicking in a script or by double-clicking in the database explorer pane), the error: "Error: Request returned as being unsuccessful." will be returned, even though the schema and table names are correct for the database showing in the database picker.

If I then change the schema / database to anything else using the database picker, then change it back to what it was when the query failed, it'll work (every time).

Log attached.
[com.hankinsoft.osx.sqlprostudio 2021-07-29--21-23-41-167.log](https://github.com/hankinsoft/SQLPro/files/6928157/com.hankinsoft.osx.sqlprostudio.2021-07-29--21-23-41-167.log)

SQLPro Studio 2021.68
Snowflake 5.29.1
macOS 11.5.1 (20G80)

**Comment by hankinsoft** [comment]
Is the the same as #827?

**Comment by jaredx435k2d0** [comment]
To be honest, I'm not sure anymore.
#827 still happens all the time.

It may have been a while now since I've seen "Error: Request returned as being unsuccessful.", though it could be because I'm so accustomed do it that I'll quickly just use CMD + D to switch to anything and then repeat it to switch back and try again.

I'll watch for next time it happens.

**Comment by hankinsoft** [comment]
Thank you. Please let me know if it happens again.
