### ISSUE TITLE
SQL Pro Studio Socket Support

### ISSUE THREAD

**Issue by alexclst** [hankinsoft/SQLPro#702]
Does SQL Pro Studio have support for connecting to MySQL databases via local sockets? I can't seem to find this anywhere in the MySQL connection configuration screens, and such a feature is important for connecting to local development environments. If this does not yet exist, is it something that is planned to be added?

**Comment by hankinsoft** [comment]
Hi. Unfortunately due to sandboxing restrictions by Apple, sockets cannot be supported. I've investigated this in the past and even opened a developer ticket with Apple and I received a `the chances of this being supported are slim to none` response. Unless Apple adds support for unix sockets from within a sandboxed app, they will not be added to SQLPro.
