### ISSUE TITLE
Switch back to results

### ISSUE THREAD

**Issue by manngo** [hankinsoft/SQLPro#716]
I don’t know whether this is new behaviour, but I don’t remember it in the past.

After an error, the lower pane naturally shows the messages pane. However, if I correct the error, I would have expected to see the results. Instead, I still get the messages pane telling me that it worked, and I need select the results pane manually.

Is there an option to switch to the results pane automatically?

**Comment by hankinsoft** [comment]
Which version of SQLPro are you using? It should already be doing so (UNLESS you have manually clicked one of the results or messages tab) as seen here:

![CleanShot 2022-01-02 at 12 06 03](https://user-images.githubusercontent.com/3160528/147881729-92506f0c-7ec7-446d-817c-809a3af77736.gif)
 
(Note the second error is because I had a selection of text selected, but it switches automatically, once fixed).

**Comment by manngo** [comment]
Thanks for your message.

I am using version Version 2021.111 (Build 110875.5).

I have included a sample. I pre-selected the results pane and ran the experiment. First statement, I get results. Second statement, I get an error message, of course. Then I re-run the first statement and only see the message. There results are there, but not yet displayed.

![sql-pro-results](https://user-images.githubusercontent.com/3796633/147912619-43c64d26-dec0-4617-bbdd-eeeda8e8ce83.gif)

The experiment works consistently, though I don’t always get this behaviour in other cases. I’m still trying to work out when.

**Comment by cwolcott** [comment]
I was able to duplicate and get it to **WORK!** 
- Start a "New Query" window
- Paste the two queries
- Execute the valid query, then the invalid (repeat)

I was able to duplicate and get it to **BREAK!** (watch video)
- Start a "New Query" window
- Paste the two queries
- Click the Messages Panel button
- Execute the valid query, then the invalid (repeat) [Only stays on Messages panel]
- Click the Results Panel button
- Execute the valid query, then the invalid (repeat) [After failing it never switches back to the Results Panel]

https://user-images.githubusercontent.com/3777526/148007967-e19763e6-758e-4c0d-851f-60bb37cad5e5.mov

**Comment by hankinsoft** [comment]
@manngo
> I pre-selected the results pane and ran the experiment.

Ahhhhh.... thats why its not switching back to results (because you clicked on one of the tabs). According to the logic, it SHOULDN't switch to the error message either. Let me think about this a bit.

@cwolcott
> I was able to duplicate and get it to BREAK! (watch video)

In your case this is expected behaviour. As SOON as the user clicks on one of the results or messages, it stops automatic switching with the assumption that you want to see what you clicked on. The only way to unset that, is to open a new tab.



What I'm thinking, is that if you click on a tab that is already selected, it clears the 'remember' state and starts automatically switching again. Would that make sense?

**Comment by manngo** [comment]
This is by of a new feature request, but it could also help with this issue, which is why I’m putting it here.

Would it be possible to add a keyboard shortcut to switch between the message and results pane? It would be a little more convenient than reaching for the mouse to select.

**Comment by TehShrike** [comment]
I am experiencing some version of this in version 2022.1 (Build 110876).  (via SetApp)

I run an insert query, it switches from the results panel to the messages panel.

I run a select query, and it does not switch me back to the messages panel.

**Comment by hankinsoft** [comment]
I've made some changes for the next build that should help resolve this. I'll be posting the build later this week or early next.

**Comment by hankinsoft** [comment]
> Would it be possible to add a keyboard shortcut to switch between the message and results pane? It would be a little more convenient than reaching for the mouse to select.

Any suggestion for the shortcut keys?

**Comment by hankinsoft** [comment]
I've submitted SQLPro Studio v2022.27 which includes a keyboard shortcut preference for switching between results and messages. It has no default set. It should be available in the App Store sometime this weekend.

**Comment by manngo** [comment]
That keyboard shortcut works perfectly for me. I haven’t had the chance to see whether the wrong tab appears, but the keyboard shortcut more than covers it. Thanks as always.

**Comment by hankinsoft** [comment]
👍🏼 - I’ll get the Setapp and website versions pushed out tomorrow as well.
