### ISSUE TITLE
Issue with Appstore License

### ISSUE THREAD

**Issue by sameerpra** [hankinsoft/SQLPro#746]
Hi,

I bought the license to SQL PRO on Apple App Store my subscription is valid till 11 January 2023. I updated the Application from APP store today and the subscription is no longer valid and it says I am using a trial version. Please fix Urgently as this is making it impossible for me to use the application for which I have paid a complete subscription fees.

**Comment by hankinsoft** [comment]
Hi,
Sorry about the issue. Can you try the steps listed here:

https://github.com/hankinsoft/SQLPro/wiki/App-Store-Subscription-not-Renewing

And let me know if that sorts everyhing out?

**Comment by sameerpra** [comment]
I tried all the things mentioned by you - unfortunately even after reinstall The SQLPro Studio App does not have an option restore purchase in version v2022.12(110883) and the option to repurchase the app subscription at 10% discount when I still have 11 months on the subscription I purchased seems really unreasonable. :(

**Comment by sameerpra** [comment]
Resolved on Email - Thanks!

**Comment by hankinsoft** [comment]
Yes, sorry about that - for anyone else who comes up against this issue:

> I see what happened. I pushed the website version rather than the app store version. I'm submitting a new build now.
> You can enter the license key:
S2-E57AE6-581502-5F0007-E9166C-BC9939-R84CRF along with any proper email address and it will unlock. Once the fixed version is back on the app store, this license will become invalid.

> Sorry for the issue!

I've got a build submitted which will resolve this, but you can use the license key above until then. If you use the above license key, it will show expiration in ~1 months from today, this is due to it being a temporary key. Once the new build is available, your App Store license should take over.

**Comment by sameerpra** [comment]
Thank You!

**Comment by sariabod** [comment]
Thank you for the quick response, this also saves me.

**Comment by hankinsoft** [comment]
The build has been available for a few days and should sort this for everyone. If anyone is still seeing any issues, please let me know.
