### ISSUE TITLE
MSSQL Export Encrypted Procedures crashes

### ISSUE THREAD

**Issue by peachesontour** [hankinsoft/SQLPro#747]
If I am doing an MSSQL database export to SQL and it encounters an encrypted procedure (See image) SQLPro will crash. An error message, or a message saying such a procedure has been skipped due to limited privileges would be an ok solution.
<img width="520" alt="Screen Shot 2022-02-23 at 17 21 26" src="https://user-images.githubusercontent.com/67612358/155403015-bc91d7fd-a5a9-42b7-8134-c1443b40e71a.png">

**Comment by hankinsoft** [comment]
Hmm, encrypted procedures are new to me. I’ll do some research and see if I can reproduce and fix the issue. Thanks for the report.

**Comment by hankinsoft** [comment]
Fixed for the next build. Rather than crash, it displays a comment saying the procedure is encrypted:

<img width="1457" alt="Screen Shot 2022-03-31 at 11 14 43 AM" src="https://user-images.githubusercontent.com/3160528/161076421-f406a042-eed8-40f2-8d58-58e9c12fd4b6.png">



I'm thinking the drop statement should be removed as well if thats the case. Any reasons you could see as why not to remove it?

**Comment by hankinsoft** [comment]
I decided to remove the drop statement for encrypted procedures:

<img width="1457" alt="Screen Shot 2022-03-31 at 11 58 31 AM" src="https://user-images.githubusercontent.com/3160528/161086281-39540138-ca08-4240-bce2-b327cdc9b914.png">

**Comment by hankinsoft** [comment]
SQLPro Studio v2022.24 is now available on the Mac app store. It will no longer crash, but instead display the above behaviour. Please let me know if I can provide anything else.
