### ISSUE TITLE
SQLite - columns resizing

### ISSUE THREAD

**Issue by scriptebob** [hankinsoft/SQLPro#777]
This just seemed to have started in the build before V2022.32. I'll be viewing the data in a table, maybe make a change and Apply. And, suddenly, every single column resizes to show only one or two characters. Then, I have to go and resize every column in order to see what the name of the column is and the data in it.

**Comment by jmadren** [comment]
Is this in SQLPro for SQLite? I've noticed this lately also. For me, it only happens if a filter is set on the table. Does it when I change/apply in the data view or by using a query. Either forces a refresh on the Data tab, which seems to be what triggers it.

Another new behaivior that's irritating, and possibly related, is these refreshes seem to occur three times in quick succession (grid disappears and reappears three times).

**Comment by hankinsoft** [comment]
Would it be possible to get a video of what your seeing?

**Comment by jmadren** [comment]
Well, turns out the disappear/reappear only hapens twice, not three times, but it's still irritating. And after watching/pausing the videos, I can see the the "flash" of the table before it disappears again is showing the "reset" version of the column widths. And when a filter is set, it doesn't "restore" the saved column sizes, whereas in the non-filter scenario it does.

The first video shows setting a filter then editing a cell and applying. Note the column widths before and after. Also note that it clears/removes the filter on apply - another thing I forgot to mention. The second video shows editing without a filter set.

I had to use Dropbox because they were too big to attach:
https://www.dropbox.com/s/o1pl83z9tzxpzu7/Data%20editing%20-%20with%20filter.mp4?dl=1
https://www.dropbox.com/s/u7pwf8rd4cm2g3s/Data%20editing%20-%20no%20filter%20.mp4?dl=1

**Comment by jmadren** [comment]
Also, the table does not remember/restore the sort order after applying a data edit.

**Comment by jmadren** [comment]
Were you able to view the videos? Any progress on this issue?

**Comment by hankinsoft** [comment]
Shoot no, I miss that. Thanks for the video's I'm investigating now.

**Comment by hankinsoft** [comment]
Fixed. Getting it submitted to Apple and Setapp now.

**Comment by hankinsoft** [comment]
Oh shoot, Apple developer endpoint is down due to the WWDC. I can't post a new build until its available. Should be able to get it posted later today or early tomorrow.

**Comment by hankinsoft** [comment]
Setapp version is now available. App Store connect is in review so should be available soon. Website version is up at https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.40.app.zip.

**Comment by jmadren** [comment]
>If you switch build type (App Store, Website, Setapp) that will happen.

I didn't switch, just allowed SetApp to update it.

**Comment by hankinsoft** [comment]
> I didn't switch, just allowed SetApp to update it.

k. I'll dig into that further as well.

**Comment by hankinsoft** [comment]
Another build submitted which should resolve the filters being reset when editing columns. I also made a change to how queries are stored - this first time it will forget your previous query, but after that it will store properly.

**Comment by jmadren** [comment]
The new version does preserve the filter when updating the table from a query, but it does not preserve the column sizes.

**Comment by hankinsoft** [comment]
Hmmm, I'm not able to reproduce the column behaviour:

![CleanShot 2022-06-09 at 14 38 29](https://user-images.githubusercontent.com/3160528/172911834-5bf73bee-e7a5-4d0a-a2c4-37fcc206b671.gif)

If possible, could I get a video again with what you're seeing? It might point in at what we are doing differently.

**Comment by jmadren** [comment]
In your video you're changing the structure, not data. Here's a video where I update existing data in a table.

Oh, and just to make sure I have the lastest version, it says Version 2022.41 (Build 4270)

https://user-images.githubusercontent.com/22791228/172918790-14772442-27e0-4d71-a854-9ba0821f7e13.mp4

.

**Comment by hankinsoft** [comment]
Would you be able to try this build: https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.42.app.zip (rather than me have every setapp user update)?

I still wasn't able to reproduce, but I re-wrote part of the column sizing code along with added logging for when its resizing. So if you reproduce again, can you also please post the log file? (Found via 'View' -> 'Logs').

**Comment by hankinsoft** [comment]
Can you try https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.2022.43.app.zip if you get the chance? Again, if it does not keep the column sizes, please post the log file.

**Comment by jmadren** [comment]
You're not able to reproduce it? So should I delete all files/settings associated with SQLPro for SQLite and try installing fresh?

**Comment by hankinsoft** [comment]
I've made some additional changes with the column resizing. If you get the chance, could you see if you are still seeing this?

**Comment by jmadren** [comment]
> I've made some additional changes with the column resizing. If you get the chance, could you see if you are still seeing this?

It is now keeping the column widths, but it still "loses" the filter settings, though the filter is still in effect. It just doesn't show the criteria that the filter is actually using. You can see this in the video I posted before - note the filter settings before and after the query is run. But the table remains filtered. Same thing happens if you select a different table then go back to the first - the filter fields are reset but the filter remains in effect.

And, it also still resets the sort order to none (which I also mentioned before and can be seen in the video). I think all of this is interconnected to how you're refreshing the table view after a query modifies data in the table.

I'm not bothered by the sort order reset, and the filter issue, while annoying or confusing at times, is not critical. You have fixed the crucial issue for me, which was the column widths. So thanks!

**Comment by hankinsoft** [comment]
Can you check the latest version and see if the filter disappearing issue is sorted?

**Comment by jmadren** [comment]
Ok, so using the same db/scenario as the video, the filter is now staying. But the sort order is still reset.

Using another db, filtering with a ">" some value on an integer column, then running a query that updates this integer column causes it to crash when returning to the Data tab. Partial crash report attached.

It also crashes on the first db if I filter with a ">" on an integer column, then update a string column in a query. So the crash does not appear to involve updating the column that's being filtered on, but just that the filter is using ">" on an integer column. Didn't try any other combinations as I don't have time. Note that the first scenario above, where it works, is filtering on a string column with "is not null", then updating that same column in the query.

One final observation: I hadn't noticed this before, but the filter function does not alter the row count shown at the bottom of the window.

[SQLPro for SQLite crash.txt](https://github.com/hankinsoft/SQLPro/files/10167761/SQLPro.for.SQLite.crash.txt)

**Comment by hankinsoft** [comment]
The first two issues should be sorted in the latest build (crash and sorting).

**Comment by jmadren** [comment]
> The first two issues should be sorted in the latest build (crash and sorting).

Confirmed.

**Comment by hankinsoft** [comment]
Latest version now updates the record label when filtering.

<img width="1698" alt="Screenshot 2022-12-13 at 8 28 52 AM" src="https://user-images.githubusercontent.com/3160528/207318419-d5fb908b-18e5-40f3-a737-cc1ca2553bb6.png">

**Comment by hankinsoft** [comment]
The latest setapp build should have this all sorted.
