### ISSUE TITLE
Feature Request: Autocomplete on Database Selection

### ISSUE THREAD

**Issue by jpoynton** [hankinsoft/SQLPro#812]
On one server I have access to about 500 databases (not tables). I often want to run the same query against a few databases before I then run against all of them. Whilst I can get to the database selector easily having a type ahead/auto complete on the databases would mean that I don't have to scroll to find the db I want.

**Comment by hankinsoft** [comment]
Hi,
I'm not exactly sure what you mean by this. Is there anyway you could provide more details? Maybe a screenshot point out where you want to be able to autocomplete the database?

**Comment by jpoynton** [comment]
![sqlpro screen](https://user-images.githubusercontent.com/13027850/185643352-bf0076fa-b7fc-4392-8576-1803e3cf145a.png)


From the pop-up that allows you to select the database for the current query tab.

**Comment by hankinsoft** [comment]
Hmmm, you should be able to basically do this already. When you open the server/database picker, right arrow so that the databases are focused, then start typing:

![CleanShot 2022-08-22 at 10 32 41](https://user-images.githubusercontent.com/3160528/185933876-1a5233dc-62c7-414c-9a75-9dfa89e4c551.gif)

**Comment by jpoynton** [comment]
Yep, thanks. Just a discoverability issue if you are using a mouse to navigate into the dialog.
