### ISSUE TITLE
Favorites disappear

### ISSUE THREAD

**Issue by ljfc** [hankinsoft/SQLPro#853]
**Describe the bug**
New favorites I have created are disappearing, and old ones are coming back.

This has happened repeatedly now. They do not always disappear right away, and sometimes survive quitting and re-opening the app. So far they have always disappeared eventually though. When they disappear, old connections I deleted are also back again.

**To Reproduce**
1. Go to 'File' > 'Connect...'
2. Click on '+' > 'Postgres'
3. Enter connection details
4. Click 'Save'
5. ... some time later ...
6. Go to 'File' > 'Connect...'
7. The saved connection has gone

**Expected behavior**
I expected the connection to remain saved.

**Environment (please complete the following information):**
 - Device: MacBook Pro (14-inch, 2021) 
 - OS: macOS 12.6.1 (21G217)
 - SQLPro for Postgres 2022.77 (Build 1047877.5)
 - PostgreSQL

**Additional context**
I have recently sorted some connections into Connection Groups, but I saw this bug before that.

The connections which disappear all have a non-standard port (25060).

iCloud Drive > SQLPro > Connections is empty
iCloud Drive > SQLPro > Favourites is empty

**Comment by ljfc** [comment]
Hello, please see attached.

[com.hankinsoft.osx.SQLProPostgres 2022-11-20--16-56-26-737.log](https://github.com/hankinsoft/SQLPro/files/10059353/com.hankinsoft.osx.SQLProPostgres.2022-11-20--16-56-26-737.log)
[connections.log](https://github.com/hankinsoft/SQLPro/files/10059354/connections.log)

The connection I added was called tb-pg-beta, and the connection which disappeared was called tp-pg-prod. I can see the change on lines 514 and 541 in `connections.log`.

**Comment by DJFriar** [comment]
I am having this issue as well. 

**Environment (please complete the following information):**

- Device: Mac Studio (2022)
- OS: macOS 13.0.1 (22A400)
- SQLPro Studio 2022.77 (Build 110948)

**Additional context**
I leave SQLPro running pretty much 24/7, but had noticed that my laptop didn't have the new connections I added. Today I closed out all my windows and opened a new one to work on a different project and noticed that my connections I had added a few weeks ago were missing.

I suspect this is new to the latest version of the app, but the prior version was 2022.15 (110886). I updated to the latest version of the app about a week ago I believe.

I have attached my logs as well. Like OP, checking iCloud Drive -> SQL Pro Connection and Favorites are both empty. Last modified date is Oct 15, 2022 for Connections (which sounds right for when I last added a new connection). Oddly, I checked by Backblaze backup and there are no files from this location saved there (I do have files from other apps that store their data in iCloud so not sure why these weren't picked up).

In the log attached, I can point out the key log entries:

_2022/11/23 03:00:05:455  setCollectionEntries with 1 sections (12 entries)._ - This is when I opened the new window. Note it shows 12 entries (which was correct).
There are then a bunch of connection errors due to some bad entries (this is normal)
_2022/11/23 03:00:26:004  onRemoveSelectedConnection_ - This is when I remove one of the bad ones since I took that server offline.
_2022/11/23 03:00:27:239  setCollectionEntries with 1 sections (6 entries)._ - And now there are 6 entries. :(


[com.hankinsoft.osx.sqlprostudio 2022-11-22--12-28-18-375.log](https://github.com/hankinsoft/SQLPro/files/10072629/com.hankinsoft.osx.sqlprostudio.2022-11-22--12-28-18-375.log)

**Comment by ljfc** [comment]
A thought on this: as a temporary mitigation, would it be possible to add a button to manually dump the current favourites to a specific file, and another to load from there? Then I could snapshot the correct state myself and fix it when syncing fails.

Also, just a note for anyone else seeing this, it looks like this is the same as #834

**Comment by ljfc** [comment]
No, that directory is empty, as is the adjacent iCloud Drive/SQLPro/Connections

**Comment by hankinsoft** [comment]
I'm just re-reading this. Is this the same issue as [#834](https://github.com/hankinsoft/SQLPro/issues/834)?

**Comment by ljfc** [comment]
Yes, I think it is – no problem if you want to close this one in favour of that!

**Comment by hankinsoft** [comment]
Can you upgrade to the latest version (on all of your systems) and monitor if this continues to happen? I've made quite a few changes and believe it might be fixed up. If you still have issues, please post them to #834.
