### ISSUE TITLE
copy/paste after reorder columns doesn't choose correct column

### ISSUE THREAD

**Issue by waroo** [hankinsoft/SQLPro#86]
In SQLPro for SQLite I went to the Data section. I reordered two columns.  I copied a field in a column but what went to the pasteboard was the text in the column that had previously occupied that spot.  I restarted the app and the problem persisted.  I reordered the columns back to the original order and copy / paste worked correctly for only the original order of columns.

**Comment by hankinsoft** [comment]
Hi, this is all fixed in the latest build. You can grab it here: https://d3fwkemdw8spx3.cloudfront.net/sqlite/SQLProSQLite.1.0.456.app.zip. Its also been submitted to the App Store and should be available within a few days. If you get the chance, please give it a try and see if that sorts the issue for you.
