### ISSUE TITLE
Change the default query that takes place when you double-click a table

### ISSUE THREAD

**Issue by brianshell** [hankinsoft/SQLPro#940]
The default query when you double-click a table is, "SELECT * FROM table_name LIMIT 1000;"

I'd like to be able to change that query to something else. . Example.:  "SELECT * FROM table_name WHERE hidden = 0 ORDER BY id DESC"

It's exceptionally rare that I might open a table and want to see the data sorted, oldest to newest, for example. 

This is SQLPro for the Mac... all my targets are MySQL.

**Comment by hankinsoft** [comment]
Thats fair. I'll investigate an option for this.

**Comment by hankinsoft** [comment]
For the next build, table tree entries will have two new context menu items:

'Run default query' and
'Set default query'

![CleanShot 2023-11-20 at 13 24 27@2x](https://github.com/hankinsoft/SQLPro/assets/3160528/df7be817-26fc-4b7e-8ffb-4b6e0cdef01a)

If you have specified a custom query, double clicking on a table (or cmd + down) will use your custom query now rather than the select. You can still use the 'select top 1,000 menu' menu item should you wish for the basic select.

I'll add another post once it's available (which should be later this week).

**Comment by hankinsoft** [comment]
A build for SQLPro Studio is now available with this via the App Store.

**Comment by brianshell** [comment]
I have no words... you are amazing!!!!! This feature will be an absolute
life-saver for me!!!!!!

Brian

**Comment by cwolcott** [comment]
Will this option eventually make it to Oracle connections?

**Comment by hankinsoft** [comment]
> I have been hoping for something like this. Will this option eventually make it to Oracle connections?

So I tried to post a build of Oracle about a month or so ago and it appears Apple is no longer accepting non-silicone targeted builds, which means currently I am unable to update SQLPro for Oracle at all. I'm <hoping> that Oracle someday soon adds support for apple silicon, but until that happens I unfortunately won't be able to provide any updates for it.

**Comment by cwolcott** [comment]
After our communications last week is this something you can add to the Oracle build. So if/when you can release an Oracle build it will be already in and ready to use.

**Comment by hankinsoft** [comment]
Hi Chris,
I thought I saw a message from you somewhere asking for this in the Oracle build we had discussed - I just fired that build up and it is already in that build. Right click a table, choose 'Set default query...'. Then once you have one set, that is what will fire when you double click the table.

**Comment by cwolcott** [comment]
Yes I was in the Old Oracle build 2023.50,  it is in build 2023.81 and I love it!!!!
